FROM python:3.11

WORKDIR /app

COPY ../api/requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY ../api /app/api

EXPOSE 8001

WORKDIR /app/api

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8001"]
