# Generated by Django 5.1.6 on 2025-02-12 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('FIAT', 'Fiat'), ('BMW', 'BMW'), ('AUDI', 'Audi'), ('NISSAN', 'Nissan'), ('CITROEN', 'Citroën')], max_length=15)),
                ('service_type', models.CharField(choices=[('SALE', 'Vente'), ('RENTAL', 'Location')], default='Vente', max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('kilometers', models.BigIntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVE', 'Validé'), ('REJECTED', 'Refusé')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sav_included', models.BooleanField(default=False)),
                ('assistance_included', models.BooleanField(default=False)),
                ('purchase_option', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.folder')),
            ],
        ),
    ]
