# Generated by Django 5.1.6 on 2025-02-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('FIAT', 'Fiat'), ('BMW', 'BMW'), ('AUDI', 'Audi'), ('NISSAN', 'Nissan'), ('CITROEN', 'Citroën')], default='Renault', max_length=15)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('kilometers', models.BigIntegerField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('SALE', 'Location'), ('RENTAL', 'Vente')], max_length=10)),
                ('test', models.CharField(choices=[('SALE', 'Location'), ('RENTAL', 'Vente')], max_length=10)),
            ],
        ),
    ]
