# Generated by Django 5.1.6 on 2025-02-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_folder_type_alter_car_brand'),
        ('app', '0003_folder_document'),
    ]

    operations = [
    ]
