# Generated by Django 5.1.6 on 2025-02-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_folder_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('FIAT', 'Fiat'), ('BMW', 'BMW'), ('AUDI', 'Audi'), ('NISSAN', 'Nissan'), ('CITROEN', 'Citroën')], default='RENAULT', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='test',
            field=models.CharField(choices=[('SALE', 'Vente'), ('RENTAL', 'Location')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SALE', 'Vente'), ('RENTAL', 'Location')], max_length=10),
        ),
        migrations.AlterField(
            model_name='folder',
            name='type',
            field=models.CharField(choices=[('SALE', 'Vente'), ('RENTAL', 'Location')], max_length=10),
        ),
    ]
