# Generated by Django 5.1.6 on 2025-02-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contract_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='pdf_file',
        ),
    ]
