# Generated by Django 5.1.6 on 2025-02-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_car_brand_alter_car_test_alter_car_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='test',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('FIAT', 'Fiat'), ('BMW', 'BMW'), ('AUDI', 'Audi'), ('NISSAN', 'Nissan'), ('CITROEN', 'Citroën')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SALE', 'Location'), ('RENTAL', 'Vente')], max_length=10),
        ),
    ]
