# Generated by Django 5.1.6 on 2025-02-12 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_car_brand_alter_car_test_alter_car_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('FIAT', 'Fiat'), ('BMW', 'BMW'), ('AUDI', 'Audi'), ('NISSAN', 'Nissan'), ('CITROEN', 'Citroën')], default='Renault', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='test',
            field=models.CharField(choices=[('SALE', 'Location'), ('RENTAL', 'Vente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SALE', 'Location'), ('RENTAL', 'Vente')], max_length=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
