# Generated by Django 5.1.6 on 2025-02-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20250212_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='test',
        ),
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='service_type',
            field=models.CharField(choices=[('SALE', 'Vente'), ('RENTAL', 'Location')], default='Vente', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('FIAT', 'Fiat'), ('BMW', 'BMW'), ('AUDI', 'Audi'), ('NISSAN', 'Nissan'), ('CITROEN', 'Citroën')], max_length=15),
        ),
    ]
