# Generated by Django 5.1.6 on 2025-02-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_car_test_alter_car_brand_alter_car_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='service_type',
            field=models.CharField(choices=[('SALE', 'Location'), ('RENTAL', 'Vente')], default='Vente', max_length=10),
        ),
    ]
