# Generated by Django 5.1.6 on 2025-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_contract_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
