# Generated by Django 5.1.6 on 2025-02-16 19:48

import app.entities.contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contract_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=app.entities.contract.models.contract_pdf_path),
        ),
    ]
