# Generated by Django 5.1.6 on 2025-02-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_car_image'),
        ('app', '0007_alter_contract_pdf_file'),
    ]

    operations = [
    ]
