# Generated by Django 5.1.6 on 2025-02-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_car_brand_alter_car_model'),
        ('app', '0008_merge_20250217_0917'),
    ]

    operations = [
    ]
